#!/usr/bin/python

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

import sys, serial
from types import StringTypes

tty = serial.Serial("/dev/ttyACM0")

parg=1
while parg < len(sys.argv):
    device=sys.argv[parg]
    state=sys.argv[parg+1]
    if state=="on":
      tty.write("T%s0126ff\n" % (device))
    else:
      tty.write("T%s012600\n" % (device))
    parg=parg+2
