#! /bin/sh

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

cd `dirname $0`

echo "<?xml version=\"1.0\"?><temperatures>" \
	`digitemp_DS2490 -c bhp.digitemprc -q -a \
		-o "<temperature onewire-id=\"%R\">%C</temperature>" | tail -n+2` \
	"</temperatures>" \
	| xsltproc bhpread.xsl -

