#!/usr/bin/python

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

import sys, serial

def get_state(tty, device):
    try:
        tty.write('s%s\r' % device)
        s = tty.read(7)[4] # s[1-8]\r\n[01]\r\n
        if s == '1':
            return 'on'
        elif s == '0':
            return 'off'
        else:
            return 'fail'
    except IndexError:
        return 'fail'

tty = serial.Serial("/dev/ttyUSB0", timeout=1)

for device, state in zip(sys.argv[1::2], sys.argv[2::2]):
    attempts = 0
    while 1:
        tty.write(('n' if state == "on" else 'f') + device + '\r')
        tty.read(4)
        if get_state(tty, device) != state:
            tty.flushOutput()
            tty.flushInput()
            if ++attempts > 3:
                sys.stderr.write("Failed to switch %s %s\n" % (device, state))
                break
        else:
            break

tty.close()

