#!/bin/sh

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

cd `dirname $0`

./bhpread >.temperatures.xml && mv .temperatures.xml temperatures.xml
cp temperatures.xml temperatures_`date +%H-%M-%S`.xml
xsltproc targets.xsl zones.xml >targets.xml
xsltproc state.xsl thermostats.xml >.state.xml && mv .state.xml state.xml
./bhpx10 -t /dev/ttyS1 `xsltproc --stringparam control-type x10 control.xsl controls.xml`

