#!/bin/sh

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

CONFIGDIR=/etc/bhp
DATADIR=/var/lib/bhp
RUNDIR=/var/run/bhp
TMP=$RUNDIR/.tmp
TEMPERATURES=$RUNDIR/temperatures.xml
STATE=$RUNDIR/state.xml
CSTATE=$RUNDIR/control-state.xml
OVERRIDES=$DATADIR/overrides.xml
LOG=/var/log/bhplog
DATE=`date -R`

if [ ! -e $RUNDIR ]; then
  mkdir -p $RUNDIR
fi

if [ ! -e $DATADIR ]; then
  mkdir -p $DATADIR
fi

for file in $TEMPERATURES $STATE $CSTATE $OVERRIDES; do
  if [ ! -e $file ]; then
    echo '<?xml version="1.0"?><empty/>' > $file
  fi
done

cd `dirname $0`
./gettemps | xsltproc --stringparam rundir $RUNDIR --stringparam configdir $CONFIGDIR bhpread.xsl - >$TMP && mv $TMP $TEMPERATURES
xsltproc --stringparam configdir $CONFIGDIR --stringparam datadir $DATADIR targets.xsl $CONFIGDIR/zones.xml >$RUNDIR/targets.xml
xsltproc --stringparam rundir $RUNDIR state.xsl $CONFIGDIR/thermostats.xml >$TMP && mv $TMP $STATE
xsltproc --stringparam rundir $RUNDIR control.xsl $CONFIGDIR/controls.xml >$TMP && mv $TMP $CSTATE
commands=$(xsltproc actuate.xsl $CSTATE 2>/dev/null)
if [ -n "$commands" ]; then
    echo "$DATE: $commands" >>$LOG
    (echo "set -e; $commands" | /bin/sh) || echo '<?xml version="1.0"?><empty/>' > $CSTATE
fi

