#!/bin/sh

# Copyright 2010 John Hedges
#
# This file is part of bhp.
#
# bhp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bhp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bhp. If not, see <http://www.gnu.org/licenses/>.

TMPDIR=/tmp/bhp
TMP=$TMPDIR/.tmp
TEMPERATURES=$TMPDIR/temperatures.xml
STATE=$TMPDIR/state.xml
CSTATE=$TMPDIR/control-state.xml
LOG=/var/log/bhplog
DATE=`date -R`
CONFDIR=/etc/bhp

if [ ! -e $TMPDIR ]; then
  mkdir -p $TMPDIR
fi

for file in $TEMPERATURES $STATE $CSTATE; do
  if [ ! -e $file ]; then
    echo '<?xml version="1.0"?><empty/>' > $file
  fi
done

cd `dirname $0`
./bhpread >$TMP && mv $TMP $TEMPERATURES
xsltproc --stringparam configdir CONFDIR targets.xsl $CONFDIR/zones.xml >$TMPDIR/targets.xml
xsltproc state.xsl $CONFDIR/thermostats.xml >$TMP && mv $TMP $STATE
xsltproc control.xsl $CONFDIR/controls.xml >$TMP && mv $TMP $CSTATE
commands=$(xsltproc actuate.xsl $CSTATE 2>/dev/null)
if [ -n "$commands" ]; then
    echo "$DATE: $commands" >>$LOG
    (echo "set -e; $commands" | /bin/sh) || echo '<?xml version="1.0"?><empty/>' > $CSTATE
fi

