#!/bin/sh

CONFIGDIR=/etc/bhp
RUNDIR=/var/run/bhp

PARAMS="--stringparam mode $1 --stringparam rundir $RUNDIR --stringparam configdir $CONFIGDIR"

/usr/bin/xsltproc $PARAMS /usr/lib/bhp/munin-thermostats.xsl $CONFIGDIR/thermostats.xml

