#!/bin/sh

# symlinked from thermometers_*

class=${0##*thermometers_}

bhpdir=/home/john/bhp

/usr/bin/xsltproc --stringparam mode "$1" --stringparam class "$class" $bhpdir/munin-thermometers.xsl $bhpdir/thermometers.xml

